services:
  postgres:
    image: postgres:17
    container_name: chores-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chores
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/db/schema:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chores-network
  chores:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: chores:latest
    container_name: chores
    environment:
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chores-network
volumes:
  pgdata:
    driver: local
networks:
  chores-network:
    driver: bridge
