// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Roommate struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	PhoneNumber string           `json:"phone_number"`
	Chore       string           `json:"chore"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}
