// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Roommate struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Email       string           `json:"email"`
	Chore       string           `json:"chore"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}
