// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Get a roommate by ID
	GetRoommateByID(ctx context.Context, id pgtype.UUID) (Roommate, error)
	// Get all roommates sorted by name and email
	GetRoommates(ctx context.Context) ([]Roommate, error)
	// Update a roommate's chore
	UpdateRoommateChore(ctx context.Context, arg UpdateRoommateChoreParams) (Roommate, error)
	// Insert or update a roommate record
	UpsertRoommate(ctx context.Context, arg UpsertRoommateParams) (Roommate, error)
}

var _ Querier = (*Queries)(nil)
